services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ams-db
          property: connectionString

  - type: web
    name: frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
